# Start-Immich.ps1 - Dynamically generated by Install-Immich.ps1

. "$PSScriptRoot\Modules\Functions.ps1"

$DistroName = $script:DistroName
$WSLUserName = $script:WSLUserName
$AppPort = 2283

$ErrorActionPreference = 'Stop'

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('INFO','WARN','ERROR')][string]$Level = 'INFO'
    )
    Write-Host "[Start-Immich] $Message"
}

Write-Log "Beginning Immich startup process..."

Write-Log "Script started with Distro: '$DistroName', ImmichDir: '$script:ImmichDirWSL', User: '$WSLUserName'."

try {
    Write-Log "Ensuring WSL distro '$DistroName' is running and initiating keep-alive..."
    wsl -d $DistroName --exec dbus-launch true
    Write-Log "WSL distro '$DistroName' keep-alive initiated."

    # WSLのIPアドレスが変わることを考慮してport-proxy設定を更新
    Write-Log "Updating port-proxy settings with current WSL IP address..."
    Set-ImmichPortProxy -AppPort $AppPort
    Set-ImmichFirewallRule -AppPort $AppPort    Start-Sleep -Seconds 5

    Write-Log "Attempting to start Immich services in '$script:ImmichDirWSL' as user '$WSLUserName'..."
    $WslCommand = "cd '$script:ImmichDirWSL' && docker compose pull && docker compose up -d"
    
    Write-Log "Executing in WSL: wsl -d $DistroName -u $WSLUserName -- bash -c $WslCommand"
    wsl -d $DistroName -u $WSLUserName -- bash -c "$WslCommand"
    Write-Log "Immich services startup command issued for '$DistroName'."

} catch {
    Write-Log "An error occurred during Immich startup: $($_.Exception.Message) | StackTrace: $($_.ScriptStackTrace)" -Level ERROR
    exit 1
}

Write-Log "Start-Immich.ps1 finished successfully."
exit 0
