# Start-Immich.ps1 - Dynamically generated by Install-Immich.ps1
Param(
    [string]$DistroName = 'Ubuntu',
    [string]$WSLUserName = 'ubuntu'
)

$ErrorActionPreference = 'Stop'

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('INFO','WARN','ERROR')][string]$Level = 'INFO'
    )
    Write-Host "[Start-Immich] $Message"
}

Write-Log "Beginning Immich startup process..."

$AbsoluteImmichDirWSL = '/opt/immich'
Write-Log "Script started with Distro: '$DistroName', ImmichDir: '$AbsoluteImmichDirWSL', User: '$WSLUserName'."

try {
    Write-Log "Ensuring WSL distro '$DistroName' is running and initiating keep-alive..."
    wsl -d $DistroName --exec dbus-launch true
    Write-Log "WSL distro '$DistroName' keep-alive initiated."

    Start-Sleep -Seconds 5

    Write-Log "Attempting to start Immich services in '$AbsoluteImmichDirWSL' as user '$WSLUserName'..."
    $WslCommand = "cd '$AbsoluteImmichDirWSL' && docker compose pull && docker compose up -d"
    
    Write-Log "Executing in WSL: wsl -d $DistroName -u $WSLUserName -- bash -c $WslCommand"
    wsl -d $DistroName -u $WSLUserName -- bash -c "$WslCommand"
    Write-Log "Immich services startup command issued for '$DistroName'."

} catch {
    Write-Log "An error occurred during Immich startup: $($_.Exception.Message) | StackTrace: $($_.ScriptStackTrace)" -Level ERROR
    exit 1
}

Write-Log "Start-Immich.ps1 finished successfully."
exit 0
